## created by @opbi/ncm
---
component:
  type: package
  name: ncm-preset-package
  description: the config preset for [package] used by ncm, maintained by OPBI to share best-practices
  keywords: standard, preset, ncm, config, template
  private: false
package:
  environment: node
  npmScope: opbi
owner:
  type: organisation
  github: opbi
  name: OPBI
  email: engineering@opbi.org
