---
version: 2

references:
  container-config-node8: &container-config-node8
    docker:
      - image: circleci/node:8
  restore-deps-cache: &restore-deps-cache
    restore_cache:
      keys:
        - yarn-packages-{{ checksum "yarn.lock" }}

jobs:
  install:
    <<: *container-config-node8
    steps:
      - checkout
      - *restore-deps-cache
      - run:
          name: Install Dependencies
          command: make install
      - save_cache:
          name: Save Yarn Package Cache
          key: yarn-packages-{{ checksum "yarn.lock" }}
          paths:
            - ~/.cache/yarn
            - node_modules
  test:
    <<: *container-config-node8
    steps:
      - checkout
      - *restore-deps-cache
      - run: make install test-coverage
      - run: cat coverage/lcov.info | npx coveralls
  release:
    <<: *container-config-node8
    steps:
      - checkout
      - *restore-deps-cache
      - run: make install build release
      - run:
          name: Update Doc GitHub Page
          command: |
            npx jsdoc2md src/** -g none > docs/API.md &&\
            npx gitbook build ./docs &&\
            git config --global user.email 'bot@gmail.com' &&\
            git config --global user.name 'bot' &&\
            npx gh-pages -d docs/_book -m '[skip ci] doc page update'

workflows:
  version: 2
  test-and-release:
    jobs:
      - test:
          filters:
            branches:
              ignore: gh-pages
      - release:
          requires:
            - test
          filters:
            branches:
              only: master
